.docker/vhost.conf
.env
README.md
config/cloudinary.yml
config/packages/fos_elastica.yaml
config/packages/monolog.yml
docker-compose.yml
src/Api/DataProvider/AbstractElasticSearchDataProvider.php

Reviewed and approved in https://github.com/aakb/ddb-cover-service/pull/1

Dcoker compose setup

---

composer.json
composer.lock

Added missing translator

---

src/Controller/SoapController.php
src/Service/MoreInfoService/AbstractMoreInfoService.php

Added "X-..." headers to response in SOAP endpoints with execution time for elastic calls.

Added profiling to soap endpoints

---

infrastructure/k8s/app-deployment.yaml
infrastructure/k8s/nginx-deployment.yaml
infrastructure/k8s/stg/app-deployment.yaml
infrastructure/k8s/stg/nginx-deployment.yaml

Ensure zero downtime when updating the application.

Added update strategy

---

infrastructure/docker/nginx/etc/confd/templates/default.conf.tmpl
infrastructure/k8s/nginx-deployment.yaml
infrastructure/k8s/stg/nginx-deployment.yaml

DDBTEAM-289: Added nginx exporter

---

.env
config/packages/fos_elastica.yaml
config/packages/monolog.yml
docker-compose.yml
infrastructure/docker/cover-service-jobs/etc/confd/templates/env.local.tmpl
infrastructure/docker/cover-service/etc/confd/templates/env.local.tmpl
infrastructure/k8s/app-deployment.yaml
infrastructure/k8s/app-import-pod.yaml
infrastructure/k8s/elasticsearch.yaml
infrastructure/k8s/jobs-deployment.yaml
infrastructure/k8s/nginx-deployment.yaml
infrastructure/k8s/stg/app-deployment.yaml
infrastructure/k8s/stg/elasticsearch.yaml

Deployed on stg setup for test.
I have not removed all the auth stuff, hence the comment out lines... if it helps this should be removed.

Remove SSL and auth on ES

---

composer.json
composer.lock
infrastructure/k8s/app-deployment.yaml
infrastructure/k8s/app-ingress.yaml
infrastructure/k8s/readme.md
infrastructure/k8s/stg/app-deployment.yaml
infrastructure/k8s/stg/app-ingress.yaml
src/Api/DataProvider/AbstractElasticSearchDataProvider.php
src/Api/DataProvider/CoverCollectionDataProvider.php
src/Api/DataProvider/CoverItemDataProvider.php
src/Controller/MetricsController.php
src/Controller/SoapController.php
src/Service/MetricsService.php
src/Service/MoreInfoService/AbstractMoreInfoService.php
src/Service/MoreInfoService/Types/MoreInfoResponse.php
symfony.lock

For the reviewer https://prometheus.io/docs/practices/naming/ ... not sure that i got it right.

Prometheus application metrics

---

infrastructure/k8s/app-ingress.yaml
infrastructure/k8s/stg/app-ingress.yaml

Started in https://github.com/danskernesdigitalebibliotek/ddb-cover-service/pull/56

Added CORS to ingress configuration

---

src/Service/MoreInfoService/AbstractMoreInfoService.php

DDBTEAM-409: Added support for new image transformations in soap

---

src/Api/DataProvider/CoverCollectionDataProvider.php
src/Api/DataProvider/CoverItemDataProvider.php
src/Api/Factory/IdentifierFactory.php

https://jira.itkdev.dk/browse/DDBTEAM-425

DDBTEAM-425: Filter images sizes base on request

---

.env
config/services.yaml
src/Api/DataProvider/AbstractElasticSearchDataProvider.php

https://jira.itkdev.dk/browse/DDBTEAM-423

DDBTEAM-423: Filter out small images

---

.env
.github/workflows/tag.yml
composer.json
config/packages/framework.yaml
infrastructure/cover-service/templates/configmap.yaml
infrastructure/cover-service/templates/ingress.yaml
infrastructure/cover-service/values.yaml
infrastructure/docker/cover-service/Dockerfile
infrastructure/docker/cover-service/docker-entrypoint.sh
infrastructure/docker/cover-service/etc/confd/templates/env.local.tmpl

https://jira.itkdev.dk/browse/DDBTEAM-472

DDBTEAM-472: Refactored cache warmup

---

infrastructure/docker/cover-service/etc/confd/templates/env.local.tmpl
infrastructure/k8s/app-deployment.yaml

https://jira.itkdev.dk/browse/DDBTEAM-497
https://symfony.com/doc/4.4/deployment/proxies.html

DDBTEAM-497: Added trusted proxies to configuration

---

src/Api/Dto/Cover.php
src/Api/Dto/ImageUrl.php

Added openapi response schema

---

config/services.yaml
src/Api/DataProvider/CoverCollectionDataProvider.php
src/Api/Elastic/SearchService.php
src/Api/OpenApi/OpenApiDecorator.php
src/EventSubscriber/SearchNoHitEventSubscriber.php
src/Security/TokenAuthenticator.php
src/Service/CoverStore/CloudinaryTransformationService.php
src/Service/NoHitService.php
src/Service/StatsLoggingService.php

See https://symfony.com/doc/4.4/service_container.html#binding-arguments-by-name-or-type
Comments welcome :-)

DDBTEAM-515: Simplified service config using 'bind'

---

composer.lock
symfony.lock

```
Package operations: 2 installs, 72 updates, 1 removal
- Removing jdorn/sql-formatter (v1.2.17)
- Updating symfony/flex (v1.6.3 => v1.7.1): Loading from cache
- Updating symfony/dotenv (v4.4.8 => v4.4.9): Loading from cache
- Updating symfony/service-contracts (v2.0.1 => v2.1.2): Loading from cache
- Updating symfony/polyfill-php73 (v1.16.0 => v1.17.0): Loading from cache
- Updating symfony/http-client-contracts (v2.1.1 => v2.1.2): Loading from cache
- Updating symfony/http-client (v4.4.8 => v4.4.9): Loading from cache
- Updating symfony/polyfill-mbstring (v1.16.0 => v1.17.0): Loading from cache
- Updating symfony/polyfill-php72 (v1.16.0 => v1.17.0): Loading from cache
- Updating symfony/polyfill-intl-idn (v1.16.0 => v1.17.0): Loading from cache
- Updating symfony/mime (v4.4.8 => …
```

Updated symfony and dependencies

---

.env
composer.json
composer.lock
config/packages/cache.yaml
config/packages/prod/cache.yaml
src/EventSubscriber/SearchNoHitEventSubscriber.php
src/Service/NoHitService.php
symfony.lock
tests/EventSubscriber/SearchNoHitEventSubscriberTest.php
tests/Security/TokenAuthenticatorTest.php
tests/Service/CoverStore/CoverStoreTransformationServiceTest.php
tests/Service/NoHitServiceTest.php

DDBTEAM-544: Added no hit cache tp api v2

---

.env
config/packages/fos_elastica.yaml

https://jira.itkdev.dk/browse/DDBTEAM-949
Update ES configuration to use index alias.
No screenshot
Requires https://github.com/danskernesdigitalebibliotek/ddb-cover-service-importers/pull/101

DDBTEAM-949: Updated config to use ES alias

---

composer.json
composer.lock
docker-compose.yml
src/Api/Factory/CoverFactory.php

https://jira.itkdev.dk/browse/DDBTEAM-1005
Updated Symfony flex....
No comment.

DDBTEAM-1005: Updated symfony flex

---

infrastructure/cover-service/templates/hpa.yaml

https://jira.itkdev.dk/browse/DDBTEAM-1015
Only helm chart changes...
If your change affects the user interface you should include a screenshot of the result with the pull request.
If you have any further comments or questions for the reviewer please add them here.

HorizontalPodAutoscaler changes in k8s 1.22

---

.env
.github/workflows/php-upgrade-pr.yaml
.github/workflows/pr.yaml
CHANGELOG.md
config/packages/api_platform.yaml
config/services.yaml
infrastructure/cover-service/templates/configmap.yaml
infrastructure/cover-service/values.yaml
infrastructure/docker/cover-service-landing/Dockerfile
infrastructure/docker/cover-service/Dockerfile
infrastructure/docker/cover-service/etc/confd/templates/env.local.tmpl
infrastructure/docker/nginx/Dockerfile
src/Api/DataProvider/CoverCollectionDataProvider.php
src/Api/Elastic/SearchElasticService.php
src/Api/OpenApi/OpenApiFactory.php
src/DataFixtures/Elastic/ElasticService.php
src/EventSubscriber/SearchNoHitEventSubscriber.php
src/Service/CoverStore/CloudinaryTransformationService.php
src/Service/NoHitService.php

https://jira.itkdev.dk/browse/DDBTEAM-948
* Update Elastic .env variables to indexing to match imports.
* Update PHP version in docker builds
* Update helm charts
* Update nginx version in docker builds
No screenshot.
If you have any further comments or questions for the reviewer please add them here.

DDBTEAM-1011: Renamed varibales and update docker, helm charts

---

CHANGELOG.md
config/cloudinary.yml
public/spec.yaml
src/Api/Dto/Cover.php
src/Api/Dto/ImageUrl.php

https://jira.itkdev.dk/browse/DDBTEAM-1031
Added support for new transformation sizes to use in DDF Next.
N/A

Added support for new transformation sizes

---

CHANGELOG.md
src/EventSubscriber/SearchNoHitEventSubscriber.php
src/Message/AbstractBaseMessage.php
tests/EventSubscriber/SearchNoHitEventSubscriberTest.php

https://jira.itkdev.dk/browse/COVER-15
Added agency id from user token to no-hit message for better mapping.
N/A
Requires: https://github.com/danskernesdigitalebibliotek/ddb-cover-service-importers/pull/135 and https://github.com/danskernesdigitalebibliotek/ddb-cover-service-upload/pull/55

Ture's ide 1 - part II
